@startmindmap DDD Patterns
* **Microservices Patterns**

** __Domain Driven Design__
*** Key Concepts
**** Bounded Context
*** Patterns
**** Aggregates
***** Groups Related Entities
***** Self Contained
***** One Root
**** Repositories
**** Domain Entity Pattern
***** State + Behavior
***** Has ID


** __Cloud Native Backing Services__
*** Types
**** Data Stores
**** Message Brokers
**** Distributed Caches
**** Monitoring
**** Identity Management
*** Characteristics
**** Attached Resources
**** Plug n Play (Strategy Pattern)
**** Plug n Play

@endmindmap
