@startmindmap DDD Patterns
* **Domain Driven Design**

** __Practices__
*** Bounded Context
*** Aggregates
*** Repositories

** __Patterns__
*** Domain Entity Pattern
**** State + Behavior
**** Has ID

*** Domain Aggregate Pattern
**** Groups Related Entities
**** Self Contained
**** One Root
@endmindmap
